import { PolicyContent } from '@/components/PolicyContent';

const termsOfServiceContent = [
  '# Bilet Buldum Terms of Service',
  'Last updated: January 4, 2024',
  '## 1. Acceptance of Terms',
  "By accessing and using the Bilet Buldum application ('the Service'), you agree to be bound by these Terms of Service ('Terms'). If you disagree with any part of these terms, you may not access the Service.",
  '## 2. Service Description',
  '### 2.1 Core Service',
  'Bilet Buldum is a ticket search and notification service that helps users find available tickets for various events and transportation services. The service includes:',
  '- Real-time ticket availability search',
  '- Automated ticket availability alerts',
  '- Customizable search preferences',
  '- Notification management',
  '### 2.2 Service Limitations',
  '- We do not sell tickets directly',
  '- Ticket availability is not guaranteed',
  '- Search results depend on third-party data accuracy',
  '- Alert delivery times may vary',
  '## 3. User Accounts',
  '### 3.1 Registration',
  'To use the Service, you must:',
  '- Be at least 13 years old',
  '- Provide accurate and complete registration information',
  '- Maintain the security of your account credentials',
  '- Promptly update any changes to your information',
  '### 3.2 Account Security',
  'You are responsible for:',
  '- Maintaining the confidentiality of your password',
  '- All activities that occur under your account',
  '- Notifying us of any unauthorized access',
  '### 3.3 Account Termination',
  'We reserve the right to terminate accounts that:',
  '- Violate these Terms',
  '- Engage in fraudulent activity',
  '- Abuse the Service',
  '- Remain inactive for extended periods',
  '## 4. User Conduct',
  '### 4.1 Prohibited Activities',
  'Users agree not to:',
  '- Violate any laws or regulations',
  '- Impersonate others or provide false information',
  '- Share misleading or fraudulent content',
  '- Attempt to access unauthorized areas of the Service',
  '- Use automated systems without our permission',
  "- Interfere with the Service's operation",
  '### 4.2 Search Alert Usage',
  'Users must:',
  '- Create reasonable numbers of search alerts',
  '- Provide accurate search criteria',
  '- Maintain active alerts responsibly',
  '- Delete or deactivate unused alerts',
  '## 5. Intellectual Property',
  '### 5.1 Our Rights',
  'All content and materials available in Bilet Buldum are protected by intellectual property rights and belong to us or our licensors, including:',
  '- Trademarks and logos',
  '- Software and code',
  '- User interface designs',
  '- Text and graphics',
  '### 5.2 User Content',
  'By submitting content to the Service, you grant us a license to use, modify, and display that content for Service purposes.',
  '## 6. Disclaimer of Warranties',
  "The Service is provided 'as is' without warranties of any kind, whether express or implied, including but not limited to:",
  '- Accuracy of search results',
  '- Availability of tickets',
  '- Reliability of notifications',
  '- Uninterrupted service access',
  '## 7. Limitation of Liability',
  'We shall not be liable for:',
  '- Indirect or consequential damages',
  '- Lost profits or data',
  '- Service interruptions',
  '- Third-party actions',
  '## 8. Changes to Terms',
  'We may modify these Terms at any time. Changes will be effective upon posting to the Service. Your continued use of the Service constitutes acceptance of modified Terms.',
  '## 9. Notifications',
  '### 9.1 Service Notifications',
  'You agree to receive notifications related to:',
  '- Ticket availability',
  '- Account security',
  '- Service updates',
  '- Policy changes',
  '### 9.2 Marketing Communications',
  'You may opt-out of marketing communications while maintaining essential service notifications.',
  '## 10. Governing Law',
  'These Terms shall be governed by and construed in accordance with the laws of Turkey, without regard to its conflict of law provisions.',
  '## 11. Dispute Resolution',
  'Any disputes arising from these Terms will be resolved through:',
  '- Good faith negotiations',
  '- Mediation if necessary',
  '- Legal proceedings in Turkish courts',
  '## 12. Contact Information',
  'For questions about these Terms, please contact us at:',
  'support@biletbuldum.com',
  'We aim to respond to all inquiries within 48 hours.',
];

export default function TermsOfService() {
  return <PolicyContent content={termsOfServiceContent} />;
}
